"""
Configuration module for EV Battery Analysis
"""
from .settings import *

__all__ = [
    'PROJECT_ROOT', 'SRC_DIR', 'CONFIG_DIR', 'DATA_DIR', 'MODELS_DIR',
    'SOH_MODEL_PATH', 'RUL_MODEL_PATH', 'TOTAL_CYCLES_EOL',
    'SOH_FORECAST_CYCLES', 'SOH_FORECAST_DAYS', 'RUL_FORECAST_CYCLES',
    'SOH_FEATURES', 'RUL_FEATURES', 'TIME_FEATURES',
    'BATTERY_STATUS_DISCHARGE', 'SOC_FULL',
    'TREND_WINDOW_SIZE', 'MAX_SOH_DROP_PER_STEP',
    'SOH_Y_AXIS_RANGE', 'RUL_Y_AXIS_MULTIPLIER'
]